version: '3.8'
services:
  backend:
    build: ./backend
    container_name: edulense-backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://edulense:edulense@postgres:5432/edulense
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ai
  ai:
    build: ./ai
    container_name: edulense-ai
    ports:
      - "8001:8001"
  postgres:
    image: postgres:15
    container_name: edulense-postgres
    restart: always
    environment:
      POSTGRES_USER: edulense
      POSTGRES_PASSWORD: edulense
      POSTGRES_DB: edulense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    image: node:20-alpine
    container_name: edulense-frontend
    command: tail -f /dev/null # Placeholder, replace with real build
    ports:
      - "3000:3000"
volumes:
  postgres_data: 