version: '3.8'
services:
  backend:
    build: ./backend
    container_name: edulense-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: edulense-frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: sqlite
    container_name: edulense-db
    volumes:
      - ./backend/data:/data
    command: ["tail", "-f", "/dev/null"] # Keeps the container running for volume 